apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  containers:
    - name: postgresql
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "secret"
          # Must specify PGDATA, otherwise PostgreSQL will raise an "initdb error"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      resources:
        limits:
          memory: "1Gi"
          cpu: "500m"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresql-data
          mountPath: "/var/lib/postgresql/data"
  volumes:
    - name: postgresql-data
      persistentVolumeClaim:
        claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
